### ISSUE TITLE
dependencies needed for net-browserify

### ISSUE THREAD

**Issue by Kiran-N** [emersion/net-browserify#13]
Do We have to add the below dependencies along with net-browserify.

![image](https://cloud.githubusercontent.com/assets/17794731/21077054/2037b9da-bf03-11e6-82f4-9f56ca435d7c.png)

**Comment by emersion** [comment]
You have to run a websocket proxy for this library to work.

**Comment by Kiran-N** [comment]
Thank you, 
Is it possible to run the proxy on browser.

**Comment by emersion** [comment]
No, it isn't possible to open arbitrary connections from the browser because of security.
