### ISSUE TITLE
isIP function in a separate file

### ISSUE THREAD

**Issue by nazar-pc** [emersion/net-browserify#14]
Could you possibly put `isIP` function into separate file and `require()` it from there?
I want to reuse it in my project, but having ~11 kB of code when I only need ~300 bytes from it is very expensive for browser build.

**Comment by emersion** [comment]
I think it's better for you to use the [`isip`](https://www.npmjs.com/package/isip) module (or another one, there's plenty of them on NPM). You won't have to download unnecessary code.

**Comment by nazar-pc** [comment]
I've already looked at others and they do not have as good implementation unfortunately. If you look at the sources mentioned module only supports IPv4 and does that incorrectly.
Would you accept a PR if I prepare one?

**Comment by emersion** [comment]
Yes, of course, no problem!

That's a shame that nobody does this right. [`isipaddress`](https://www.npmjs.com/package/isipaddress) mentions RFCs, maybe it's better than the others?

**Comment by emersion** [comment]
Also, these regex come from Node's source. Maybe there are newer versions upstream.

**Comment by nazar-pc** [comment]
isipaddress seems to be a solid one, thank you very much!
