### ISSUE TITLE
Unable to use as a client

### ISSUE THREAD

**Issue by forevermatt** [emersion/net-browserify#6]
This may simply be a request that the readme be clarified.  I'm not sure.

It appears that to use this as a client (ignoring the proxy capabilities), you would do the following: 

```
var net = require('net-browserify');

var socket = net.connect({
    host: 'google.com',
    port: 80
});

socket.on('connect', function () {
    console.log('Connected to google.com!');
});
```

However, the `net` object that gets returned by `require` does not have a `connect()` method.  The value being returned by `require('net-browserify')` apparently is not an equivalent of that returned by `require('net')`.

I could very well have misunderstand the instructions, but following what I understood to be the way to use this as a client (as shown above) makes it look like there is a bug related to requiring net-browserify directly.

**Comment by emersion** [comment]
The object returned by `require('net-browserify')` is an equivalent for `net` only if used with browserify (see https://github.com/emersion/net-browserify/blob/master/package.json#L11). If you want to use `net-browserify` with Node, you can `require('net-browserify/browser')`.

**Comment by forevermatt** [comment]
Thanks
