### ISSUE TITLE
connection closed with Caddy as reverse proxy

### ISSUE THREAD

**Issue by edrex** [emersion/net-browserify#7]
With the Caddy webserver in front, the example app shows "connection closed" after the first frame.

to repro, start the example app, place the following Caddyfile in the root, and run `caddy`

```
localhost
proxy /api/vm/net 127.0.0.1:3000 {
  websocket
}
```

I'm not sure which side is off-spec, but opening the issue here to increase visibility (@mholt)

PS: I first saw this behavior downstream in [quassel-webserver](https://github.com/magne4000/quassel-webserver) (@magne4000)

**Comment by mholt** [comment]
Related to https://github.com/mholt/caddy/issues/746 I wonder?

**Comment by edrex** [comment]
@mholt looks like no, I can't reproduce that one in my env.

**Comment by edrex** [comment]
Not 100% yet, but it's looking like this is on the Caddy side. Closing before I forget.
